### ISSUE TITLE
Service 'web' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder081051733/config/secret.exs: no such file or directory

### ISSUE THREAD

**Issue by PopeRigby** [angristan/docker-pleroma#13]
I'm getting this error when trying to build Pleroma. I have `/config/secret.exs`, so I don't know what it's complaining about.

This is my current file structure:

```
.
├── build
│   └── Dockerfile
├── config
│   └── secret.exs
├── db (just a bunch of postgres stuff in here)
├── docker-compose.yml
└── uploads
```

This is my `docker-compose.yml`:

```
version: '2.3'

services:
  db:
    image: postgres:9.6-alpine
    container_name: pleroma-db
    restart: always
    environment:
      POSTGRES_USER: pleroma
      POSTGRES_PASSWORD: pleroma
      POSTGRES_DB: pleroma
    volumes:
      - ./db:/var/lib/postgresql/data

  web:
    build: ./build
    image: pleroma
    container_name: pleroma-web
    restart: always
    ports:
      - '127.0.0.1:4000:4000'
    volumes:
      - ./uploads:/pleroma/uploads
    depends_on:
      - db
```
